# Generated by Django 3.2.9 on 2021-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20211112_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='domestic_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='international_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='years_of_activity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
