# Generated by Django 3.2.9 on 2021-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20211113_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='meta_title'),
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='meta_title'),
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_title_fa',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='meta_title'),
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_title_ku',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='meta_title'),
        ),
    ]
