# Generated by Django 3.2.9 on 2021-11-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20211123_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address_ar',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_en',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_fa',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='setting',
            name='address_ku',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='address'),
        ),
    ]
