# Generated by Django 3.2.9 on 2021-11-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
