# Generated by Django 3.2.9 on 2021-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211121_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_on_time',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
