# Generated by Django 3.2.9 on 2021-11-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211121_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_on_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
