# Generated by Django 3.2.9 on 2021-11-11 07:49

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_fa', models.CharField(max_length=60, verbose_name='category')),
                ('category_ar', models.CharField(max_length=60, verbose_name='category')),
                ('category_ku', models.CharField(max_length=60, verbose_name='category')),
                ('category_en', models.CharField(max_length=60, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Products-img/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, max_length=80, null=True, verbose_name='name')),
                ('name_ar', models.CharField(blank=True, max_length=80, null=True, verbose_name='name')),
                ('name_ku', models.CharField(blank=True, max_length=80, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='name')),
                ('description_fa', django_quill.fields.QuillField(verbose_name='description')),
                ('description_ar', django_quill.fields.QuillField(verbose_name='description')),
                ('description_ku', django_quill.fields.QuillField(verbose_name='description')),
                ('description_en', django_quill.fields.QuillField(verbose_name='description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('image', models.ManyToManyField(to='products.Image')),
            ],
        ),
    ]
