# Generated by Django 3.2.9 on 2021-11-22 16:19

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=django_quill.fields.QuillField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=django_quill.fields.QuillField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fa',
            field=django_quill.fields.QuillField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ku',
            field=django_quill.fields.QuillField(verbose_name='توضیحات'),
        ),
    ]
